baseURL = 'https://Asad-Ismail.github.io/'
languageCode = 'en-us'
title = 'Asad Ismail'
theme = "hugo-coder"

paginate = 20

[markup.highlight]
style = "github-dark"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Content"
    url = "/content/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6


[params]
  enableFontAwesome = true
  author = "Asad Ismail"
  info = "Machine Learning Engineer | AI Researcher | Building intelligent systems with deep learning and PyTorch"
  description = "Asad Ismail's personal website - Machine Learning Engineer and AI researcher specializing in deep learning, computer vision, and natural language processing"
  keywords = "machine learning, ML engineer, AI, deep learning, PyTorch, TensorFlow, computer vision, NLP, neural networks"
  avatarurl = "images/my_pic.jpg"
  #gravatar = "asadismaeel@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"


# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Asad-Ismail/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/asad-ismail/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/AsadIsmailML"
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 4
  url = "mailto:asadismaeel@gmail.com"
[[params.social]]
  name = "Substack"
  icon = "fa-brands fa-substack fa-2x"
  weight = 5
  url = "https://asadismail.substack.com"
[[params.social]]
  name = "YouTube"
  icon = "fa-brands fa-youtube fa-2x"
  weight = 6
  url = "https://www.youtube.com/@AsadIsmailML"
